# Generated by Django 5.2.17 on 2026-08-14 11:20

import django.core.validators
import django.db.models.deletion
import references.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('default_style', models.CharField(choices=[('abnt', 'ABNT (NBR 6023)'), ('apa', 'APA 7ª edição'), ('vancouver', 'Vancouver'), ('chicago', 'Chicago autor-data'), ('harvard', 'Harvard'), ('ieee', 'IEEE')], default='abnt', max_length=20, verbose_name='estilo padrão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'projeto',
                'verbose_name_plural': 'projetos',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included', models.BooleanField(default=True, verbose_name='incluir na lista')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='posição')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='adicionada em')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_references', to='references.project')),
            ],
            options={
                'verbose_name': 'referência do projeto',
                'verbose_name_plural': 'referências do projeto',
                'ordering': ['position', 'added_at'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_type', models.CharField(choices=[('journal_article', 'Artigo de periódico'), ('book', 'Livro'), ('book_chapter', 'Capítulo de livro'), ('website', 'Página da internet'), ('thesis', 'Dissertação ou tese'), ('conference', 'Trabalho em evento'), ('report', 'Relatório'), ('other', 'Outro')], default='journal_article', max_length=30, verbose_name='tipo')),
                ('authors', models.JSONField(blank=True, default=list, verbose_name='autores')),
                ('editors', models.JSONField(blank=True, default=list, verbose_name='editores')),
                ('title', models.CharField(max_length=600, verbose_name='título')),
                ('subtitle', models.CharField(blank=True, max_length=600, verbose_name='subtítulo')),
                ('year', models.CharField(blank=True, max_length=20, verbose_name='ano')),
                ('container_title', models.CharField(blank=True, max_length=500, verbose_name='periódico, livro ou evento')),
                ('publisher', models.CharField(blank=True, max_length=300, verbose_name='editora ou instituição')),
                ('publisher_place', models.CharField(blank=True, max_length=180, verbose_name='local de publicação')),
                ('edition', models.CharField(blank=True, max_length=50, verbose_name='edição')),
                ('volume', models.CharField(blank=True, max_length=50, verbose_name='volume')),
                ('issue', models.CharField(blank=True, max_length=50, verbose_name='número')),
                ('pages', models.CharField(blank=True, max_length=80, verbose_name='páginas')),
                ('doi', models.CharField(blank=True, max_length=300, verbose_name='DOI')),
                ('url', models.URLField(blank=True, max_length=1000, verbose_name='URL')),
                ('access_date', models.DateField(blank=True, null=True, verbose_name='data de acesso')),
                ('language', models.CharField(blank=True, default='pt', max_length=30, verbose_name='idioma')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('source_kind', models.CharField(choices=[('manual', 'Cadastro manual'), ('pdf', 'Arquivo PDF'), ('docx', 'Arquivo DOCX'), ('pptx', 'Arquivo PPTX'), ('url', 'URL')], default='manual', max_length=20, verbose_name='origem')),
                ('source_file', models.FileField(blank=True, upload_to=references.models.reference_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'pptx'])], verbose_name='arquivo original')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='nome original')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='URL de origem')),
                ('extraction_status', models.CharField(choices=[('review', 'Revisão necessária'), ('reviewed', 'Revisada'), ('failed', 'Falha na extração')], default='review', max_length=20, verbose_name='status da extração')),
                ('extraction_warnings', models.JSONField(blank=True, default=list, verbose_name='avisos da extração')),
                ('normalized_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to=settings.AUTH_USER_MODEL)),
                ('projects', models.ManyToManyField(related_name='references', through='references.ProjectReference', to='references.project')),
            ],
            options={
                'verbose_name': 'referência',
                'verbose_name_plural': 'referências',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='projectreference',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='references.reference'),
        ),
        migrations.AddIndex(
            model_name='reference',
            index=models.Index(fields=['owner', 'doi'], name='references__owner_i_6a8847_idx'),
        ),
        migrations.AddIndex(
            model_name='reference',
            index=models.Index(fields=['owner', 'updated_at'], name='references__owner_i_a4f0ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectreference',
            constraint=models.UniqueConstraint(fields=('project', 'reference'), name='unique_reference_per_project'),
        ),
    ]
