# Generated by Django 5.2.17 on 2026-08-13 12:01

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monograph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Em elaboração'), ('review', 'Em revisão'), ('finished', 'Concluída')], default='draft', max_length=16)),
                ('author_name', models.CharField(blank=True, max_length=180)),
                ('institution_line_1', models.CharField(default='IGREJA PRESBITERIANA DO BRASIL - IPB', max_length=180)),
                ('institution_line_2', models.CharField(default='JUNTA DE EDUCAÇÃO TEOLÓGICA - JET', max_length=180)),
                ('institution_line_3', models.CharField(default='JUNTA REGIONAL DE EDUCAÇÃO TEOLÓGICA - JURET/RECIFE', max_length=180)),
                ('institution_line_4', models.CharField(default='SEMINÁRIO PRESBITERIANO DO NORTE - SPN', max_length=180)),
                ('course_name', models.CharField(default='CURSO LIVRE DE BACHARELADO EM TEOLOGIA', max_length=180)),
                ('city', models.CharField(default='Recife - PE', max_length=100)),
                ('year', models.PositiveSmallIntegerField(default=2026, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2200)])),
                ('advisor_name', models.CharField(blank=True, max_length=180)),
                ('advisor_title', models.CharField(blank=True, default='Rev.', max_length=80)),
                ('nature_text', models.TextField(default='Monografia apresentada ao Seminário Presbiteriano do Norte - SPN, em cumprimento às exigências para a conclusão do Curso Livre de Bacharelado em Teologia.')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('theme', models.TextField(blank=True)),
                ('delimitation', models.TextField(blank=True)),
                ('research_problem', models.TextField(blank=True)),
                ('hypothesis', models.TextField(blank=True)),
                ('general_objective', models.TextField(blank=True)),
                ('specific_objectives', models.TextField(blank=True)),
                ('justification', models.TextField(blank=True)),
                ('methodology', models.TextField(blank=True)),
                ('planning_keywords', models.CharField(blank=True, max_length=500)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('examiner_internal_name', models.CharField(blank=True, max_length=180)),
                ('examiner_internal_title', models.CharField(blank=True, default='Rev.', max_length=80)),
                ('examiner_internal_institution', models.CharField(blank=True, default='Seminário Presbiteriano do Norte - SPN', max_length=180)),
                ('examiner_external_name', models.CharField(blank=True, max_length=180)),
                ('examiner_external_title', models.CharField(blank=True, default='Rev.', max_length=80)),
                ('examiner_external_institution', models.CharField(blank=True, max_length=180)),
                ('dedication', models.TextField(blank=True)),
                ('acknowledgements', models.TextField(blank=True)),
                ('epigraph_text', models.TextField(blank=True)),
                ('epigraph_author', models.CharField(blank=True, max_length=180)),
                ('confessional_title', models.CharField(blank=True, default='CONFISSÃO DE FÉ DE WESTMINSTER', max_length=300)),
                ('confessional_subtitle', models.CharField(blank=True, max_length=300)),
                ('confessional_content', models.TextField(blank=True)),
                ('confessional_references', models.TextField(blank=True)),
                ('abstract_pt', models.TextField(blank=True)),
                ('keywords_pt', models.CharField(blank=True, max_length=500)),
                ('abstract_en', models.TextField(blank=True)),
                ('keywords_en', models.CharField(blank=True, max_length=500)),
                ('abbreviations', models.TextField(blank=True)),
                ('symbols', models.TextField(blank=True)),
                ('introduction', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('glossary', models.TextField(blank=True)),
                ('appendices', models.TextField(blank=True)),
                ('annexes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monographs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_key', models.CharField(max_length=120)),
                ('action', models.CharField(choices=[('review', 'Análise acadêmica'), ('polish', 'Aprimoramento de redação'), ('outline', 'Sugestão de estrutura'), ('translate', 'Tradução acadêmica')], max_length=20)),
                ('original_text', models.TextField(blank=True)),
                ('proposed_text', models.TextField(blank=True)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_revisions', to=settings.AUTH_USER_MODEL)),
                ('monograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_revisions', to='works.monograph')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=180)),
                ('onboarding_seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('guidance_key', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='works.monograph')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='works.section')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('book', 'Livro'), ('article', 'Artigo'), ('chapter', 'Capítulo de livro'), ('thesis', 'Tese ou dissertação'), ('other', 'Outro')], default='other', max_length=16)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('authors', models.JSONField(blank=True, default=list)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('publisher', models.CharField(blank=True, max_length=250)),
                ('edition', models.CharField(blank=True, max_length=80)),
                ('container_title', models.CharField(blank=True, max_length=500)),
                ('volume', models.CharField(blank=True, max_length=50)),
                ('issue', models.CharField(blank=True, max_length=50)),
                ('pages', models.CharField(blank=True, max_length=80)),
                ('doi', models.CharField(blank=True, max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=80)),
                ('url', models.URLField(max_length=1000)),
                ('language', models.CharField(blank=True, max_length=30)),
                ('provider', models.CharField(max_length=60)),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('access_date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='works.monograph')),
            ],
            options={
                'ordering': ['title', 'year'],
                'constraints': [models.UniqueConstraint(fields=('monograph', 'url'), name='unique_publication_url_per_monograph')],
            },
        ),
    ]
