# Generated by Django 5.2.17 on 2026-08-13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferenceEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(max_length=4000)),
                ("source_filename", models.CharField(blank=True, max_length=255)),
                ("checksum", models.CharField(max_length=64)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("monograph", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reference_entries", to="works.monograph")),
            ],
            options={"ordering": ["order", "id"]},
        ),
        migrations.CreateModel(
            name="CitationNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("marker", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("target_key", models.CharField(max_length=120)),
                ("sequence", models.PositiveIntegerField()),
                ("reference_text", models.TextField(max_length=4000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("monograph", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="citation_notes", to="works.monograph")),
                ("publication", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="citation_notes", to="works.publication")),
                ("reference_entry", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="citation_notes", to="works.referenceentry")),
            ],
            options={"ordering": ["sequence", "id"]},
        ),
        migrations.AddConstraint(
            model_name="referenceentry",
            constraint=models.UniqueConstraint(fields=("monograph", "checksum"), name="unique_imported_reference_per_monograph"),
        ),
        migrations.AddConstraint(
            model_name="citationnote",
            constraint=models.UniqueConstraint(fields=("monograph", "sequence"), name="unique_citation_sequence_per_monograph"),
        ),
    ]
